name: pybrain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipython
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda
  - nb_conda_kernels
  - nbconvert=5
  - nbformat
  - numpy=1.19.0
  - pandas
  - pip
  - pytest
  - scikit-image
  - scikit-learn==0.20
  - scipy
  - seaborn
  - statsmodels
  - traits
  - dipy
  - bokeh
  - plotly
  - pip:
    - atlasreader
    - datalad[full]
    - duecredit
    - fury
    - keras
    - joblib
    - nbval
    - nibabel
    - niflow-nipype1-workflows
    - nilearn
    - nipy
    - nipype
    - nistats
    - nitime
    - nose
    - pingouin==0.2.4
    - pybids==0.8
    - tensorflow
    - vtk
